### ISSUE TITLE
A Funder can claim all hypercerts they are eligible for (even from different Projects) in a single transaction

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#18]

**Comment by ryscheng** [comment]
Carl's concern: on average funders will have >12 different hypercerts they are eligible for. So this is probably important for gas efficiency, otherwise, we'd expect a large drop-off rate.

**Comment by ryscheng** [comment]
CC @Jipperism @bitbeckers this speaks to a question you guys had yesterday. I think we originally underestimated how important this is.

**Comment by Jipperism** [comment]
After a quick discussion with @bitbeckers solving this would entail creating `batchMintFractionsFromAllowlist()` method on the contract. The problem would be to gather the claims that a specific user is eligible for. Using the graph for this would include:

- read file from IPFS
- parse JSON blob using the graph
- read out addresses from the constructed tree
- emit graph events for each user

If TheGraph doesn't support this it wouldn't be possible as it cannot be done inside the contract.
IMO a faster approach would be to introduce some sort of data storage, and store it there by wallet address. Mostly because there are less unknown factors.

**Comment by ryscheng** [comment]
@ccerv1 has a good point that we can use the Gitcoin graph instance to query which projects a user has funded, then use that as a hint to know which allowlists fetch from IPFS.

**Comment by ccerv1** [comment]
@bitbeckers related to issue #19, do you have any thoughts on estimating gas fees for a `batchMintFractionsFromAllowlist()` method?

**Comment by ccerv1** [comment]
@ryscheng @Jipperism is this complete now?

**Comment by Jipperism** [comment]
Yes, this is completed and can be closed.
